# Generated by Django 4.1.3 on 2022-11-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_resposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='post',
            new_name='comentario',
        ),
    ]
