# Generated by Django 4.1.3 on 2022-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_postagem_resposta_postagem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='voto',
            field=models.IntegerField(default=0),
        ),
    ]
