# Generated by Django 4.1.3 on 2022-11-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_postagem1_resposta_postage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resposta',
            old_name='postage',
            new_name='postagem',
        ),
    ]
